# Generated by Django 5.0 on 2025-10-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year_published', models.IntegerField(verbose_name='Год издания')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка книги')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF файл')),
                ('status', models.CharField(choices=[('available', 'Свободна'), ('reserved', 'Забронирована'), ('taken', 'Выдана')], default='available', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('taken', 'Книга выдана'), ('returned', 'Книга возвращена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус бронирования')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('taken_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-reservation_date'],
            },
        ),
    ]
