# Generated by Django 5.0 on 2025-12-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата получения'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Планируемое время получения'),
        ),
    ]
